name: 'GitHub Action for Build'
description: 'Build docker image'
inputs:
  dockerfile:
    description: 'specify Dockerfile to use'
    required: false
    default: 'Dockerfile'
  docker-build-args:
    description: 'docker build-args arguments'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -f ${{ inputs.dockerfile }}
    - ${{ inputs.docker-build-args }}
branding:
  icon: 'package'
  color: 'green'